import fs from "node:fs";
import path from "node:path";

export class ContextAssembler {
  #paths;
  #memory;
  #bus;
  #graph;
  #refreshTimer;
  #refreshInterval;

  constructor(paths, memory, bus, graph) {
    this.#paths = paths;
    this.#memory = memory;
    this.#bus = bus;
    this.#graph = graph;
    this.#refreshInterval = 60_000;
    this.#refreshTimer = null;
    if (bus) {
      bus.on("task:completed", () => this.#writeCurrentContext());
      bus.on("task:failed", () => this.#writeCurrentContext());
    }
  }

  startAutoRefresh() {
    this.#writeCurrentContext();
    this.#refreshTimer = setInterval(() => this.#writeCurrentContext(), this.#refreshInterval);
  }

  stopAutoRefresh() {
    if (this.#refreshTimer) {
      clearInterval(this.#refreshTimer);
      this.#refreshTimer = null;
    }
  }

  assemble(task) {
    return {
      task,
      memory: {
        recentEpisodes: this.#memory.recentEpisodes(5),
        semantic: this.#memory.semanticSearch(task.goal || task.description || "", 10)
      },
      architecture: this.#loadArchitectureText(),
      graph: this.#graph ? this.#graph.toHumanString() : "No graph data available.",
      incidents: this.#getRecentIncidents(),
      decisions: this.#getRecentDecisions(10),
      failures: this.#getFailurePatterns(10)
    };
  }

  #writeCurrentContext() {
    try {
      const contextDir = this.#paths.contextDir;
      if (!fs.existsSync(contextDir)) {
        fs.mkdirSync(contextDir, { recursive: true });
        return;
      }

      const projectProfile = this.#getProjectProfile();
      const activeTasks = this.#getActiveTasks();
      const activeSessions = this.#getActiveSessions();
      const recentMemory = this.#memory.recentEpisodes(5);
      const recentIncidents = this.#getRecentIncidents();
      const currentGraph = this.#graph ? this.#graph.toHumanString() : "No graph data available.";
      const architecture = this.#loadArchitectureText();
      const workState = this.#getWorkState();
      const recentDecisions = this.#getRecentDecisions();
      const failurePatterns = this.#getFailurePatterns();

      const content = [
        "# Current Context",
        "",
        "*Auto-generated by cogd. Do not edit manually.*",
        "",
        "---",
        "",
        "## Project Profile",
        projectProfile,
        "",
        "---",
        "",
        "## Work State",
        "",
        ...(workState?.active
          ? [
              `**Active Task:** ${workState.goal || "—"}`,
              `**Status:** ${workState.status || "—"}`,
              `**Next Action:** ${workState.nextAction || "—"}`,
              `**Hypothesis:** ${workState.hypothesis || "—"}`,
              `**Active Files:** ${workState.activeFiles?.length > 0 ? workState.activeFiles.join(", ") : "none"}`,
              `**Risks:** ${workState.risks?.length > 0 ? workState.risks.join("; ") : "none identified"}`,
              `**Branch:** ${workState.branch || "unknown"}`,
              `**Updated:** ${workState.updatedAt || "—"}`
            ]
          : ["No active work state."]),
        "",
        "---",
        "",
        "## Active Tasks",
        "",
        ...(activeTasks.length > 0
          ? activeTasks.map((t) => `- [${t.status}] **${t.goal}** (ID: ${t.id})`)
          : ["No other active tasks."]),
        "",
        "---",
        "",
        "## Active Sessions",
        "",
        ...(activeSessions.length > 0
          ? activeSessions.map((s) => `- **${s.provider}** (${s.mode}) on task \`${s.task}\` (started: ${s.startedAt})`)
          : ["No active sessions."]),
        "",
        "---",
        "",
        "## Recent Memory (Episodic)",
        "",
        ...(recentMemory.length > 0
          ? recentMemory.map((e) => `- **${e.goal}** [${e.status}] (${e.completedAt || e.createdAt})`)
          : ["No recent episodic memory."]),
        "",
        "---",
        "",
        "## Architecture Overview",
        "",
        architecture ? architecture.slice(0, 1000) : "No architecture context loaded.",
        "",
        "---",
        "",
        "## Knowledge Graph",
        "",
        currentGraph,
        "",
        "---",
        "",
        "## Recent Incidents",
        "",
        ...(recentIncidents.length > 0 ? recentIncidents : ["None."]),
        "",
        "---",
        "",
        "## Recent Decisions",
        "",
        ...(recentDecisions.length > 0
          ? recentDecisions.map((d) => `- **${d.title}**: ${d.decision}${d.context ? ` (${d.context})` : ""}`)
          : ["None."]),
        "",
        "---",
        "",
        "## Failure Patterns",
        "",
        ...(failurePatterns.length > 0
          ? failurePatterns.map((f) => `- [${f.toolchain}] ${f.message} — \`${f.fingerprint}\``)
          : ["None."]),
      ];

      const currentPath = path.join(contextDir, "current.md");
      fs.writeFileSync(currentPath, content.join("\n") + "\n");
    } catch (err) {
      console.error(`[context] Failed to write current.md: ${err.message}`);
    }
  }

  #getActiveTasks() {
    const tasksDir = this.#paths.tasksDir;
    if (!fs.existsSync(tasksDir)) return [];
    let files;
    try {
      files = fs.readdirSync(tasksDir);
    } catch {
      return [];
    }
    const active = [];
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      try {
        const t = JSON.parse(fs.readFileSync(path.join(tasksDir, f), "utf8"));
        if (t.status === "active" || t.status === "executing") {
          active.push(t);
        }
      } catch {
        continue;
      }
    }
    return active;
  }

  #getActiveSessions() {
    const sessionsDir = this.#paths.sessionsActiveDir;
    if (!sessionsDir || !fs.existsSync(sessionsDir)) return [];
    let files;
    try {
      files = fs.readdirSync(sessionsDir);
    } catch {
      return [];
    }
    return files
      .filter((f) => f.endsWith(".json"))
      .map((f) => {
        try {
          return JSON.parse(fs.readFileSync(path.join(sessionsDir, f), "utf8"));
        } catch {
          return null;
        }
      })
      .filter(Boolean);
  }

  #getRecentIncidents() {
    const incidentsDir = this.#paths.incidentsDir;
    if (!incidentsDir || !fs.existsSync(incidentsDir)) return [];
    let files;
    try {
      files = fs.readdirSync(incidentsDir);
    } catch {
      return [];
    }
    return files
      .sort()
      .slice(-5)
      .map((f) => {
        try {
          const data = JSON.parse(fs.readFileSync(path.join(incidentsDir, f), "utf8"));
          return `- ${data.title || data.id}: ${data.summary || ""}`;
        } catch {
          return null;
        }
      })
      .filter(Boolean);
  }

  #loadArchitectureText() {
    const archFile = path.join(this.#paths.contextDir, "architecture.md");
    if (fs.existsSync(archFile)) {
      return fs.readFileSync(archFile, "utf8");
    }
    const docsArch = path.join(this.#paths.docsDir, "architecture-overview.md");
    if (fs.existsSync(docsArch)) {
      return fs.readFileSync(docsArch, "utf8");
    }
    return "";
  }

  #getWorkState() {
    const wsFile = path.join(this.#paths.workStateDir, "active.json");
    if (!fs.existsSync(wsFile)) return null;
    try {
      return JSON.parse(fs.readFileSync(wsFile, "utf8"));
    } catch {
      return null;
    }
  }

  #getRecentDecisions(limit = 5) {
    const decFile = path.join(this.#paths.decisionsDir, "decisions.jsonl");
    if (!fs.existsSync(decFile)) return [];
    try {
      const content = fs.readFileSync(decFile, "utf8").trim();
      if (!content) return [];
      return content.split("\n").filter(Boolean).slice(-limit).map((l) => JSON.parse(l));
    } catch {
      return [];
    }
  }

  #getFailurePatterns(limit = 5) {
    const failFile = path.join(this.#paths.failureMemoryDir, "failure_patterns.jsonl");
    if (!fs.existsSync(failFile)) return [];
    try {
      const content = fs.readFileSync(failFile, "utf8").trim();
      if (!content) return [];
      return content.split("\n").filter(Boolean).slice(-limit).map((l) => JSON.parse(l));
    } catch {
      return [];
    }
  }

  #getProjectProfile() {
    const protocolPath = path.join(this.#paths.agentRoot, "PROTOCOL.md");
    if (!fs.existsSync(protocolPath)) return "No project profile found in PROTOCOL.md.";
    
    try {
      const content = fs.readFileSync(protocolPath, "utf8");
      const start = content.indexOf("## Project Profile");
      if (start === -1) return "Project profile section not found in PROTOCOL.md.";
      
      const nextSection = content.indexOf("---", start);
      const profile = nextSection !== -1 
        ? content.slice(start + 18, nextSection).trim()
        : content.slice(start + 18).trim();
        
      return profile || "Profile section is empty.";
    } catch {
      return "Error reading project profile.";
    }
  }
}
